### ISSUE TITLE
Implement Immunization and Growth Monitoring Monthly Reports

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#51]
- [x] These reports are accessible from the side menu [ see issue #50]

- [x] The **Immunization and Growth Monitoring Monthly Reports** page consists of 2 columns/tabs: Draft Monthly and Sent Monthly - similar to [this issue](https://github.com/OpenSRP/opensrp-client/issues/519) and [this issue](https://github.com/OpenSRP/opensrp-client/issues/520))

- [x] Tapping on Sent Monthly will open the **Sent Monthly** view - #52. 

- [x] Tapping on the Draft Monthly will open the **Draft Monthly** view.

- [x] Tapping on the top left-hand user initials or swiping from the left navigates user back to the reports page.

- [x] If there are available draft reports, the **Start New Report** button will be blue and active. 

![image](https://user-images.githubusercontent.com/58034047/94532808-04b77e80-0247-11eb-848f-2d5d8cc7eae2.png)

- [x] Tapping on the blue button will show a list of all available reports. Reports become available to fill out on the 1st of each calendar month for the previous month's report. For e.g. on October 1st, 2020, the September 2020 report becomes available to select. If there are multiple reports shown, they are listed in reverse chronological order.

![image](https://user-images.githubusercontent.com/58034047/94532706-e2256580-0246-11eb-8a6d-54632630f93e.png)

- [x] If there are no reports available, the **Start New report** will be grey and inactive.

![image](https://user-images.githubusercontent.com/58034047/94532877-19941200-0247-11eb-8185-a25c63f1aad9.png)

- [x] Once a user selects the report they want to open, they will be directed to the report page based on the data dictionary [here.](https://docs.google.com/spreadsheets/d/1MdQvZ1VirLGqgNwxpBPvFmVfA7HQT-gWrMXWOoDxyIA/edit#gid=571946050). The section headers will be: 

- Vaccination activity at different ages
- Vaccine utilization report
- Children protected against tetanus at birth
- Rubella vaccination for women giving birth for the first time
- Children with an adequate number of growth measurements
- Children with at least 1 previous episode of undernutrition
- Children diagnosed as malnourished according to the weighing of the day

Note! All indicators are uneditable except for the areas highlighted in red on the data dictionary (vaccine_doses_administered_dt15to49, vials_used, doses_per_vial). 

![image](https://user-images.githubusercontent.com/58034047/94534571-37fb0d00-0249-11eb-8104-c556c1bedf70.png)

- [x] There is a **Save** button at the top of the page. Tapping on this will save the report and navigate the user back to the **Draft Reports** view. The report can be seen on this view with a date stamp of when it was last edited. - #63 

- [x] At the end of the report, there is an active **Confirm Button**. Tapping on this button will prompt the user whether they want to send the report. The message will have date stamp [today's date] and the sender's name [app user]. 

![image](https://user-images.githubusercontent.com/58034047/94534823-827c8980-0249-11eb-9f09-4eb626064953.png)

![image](https://user-images.githubusercontent.com/58034047/94535230-ff0f6800-0249-11eb-8a4f-4b5dd3be6094.png)

- [x] Tapping on **Send** syncs the report to the server. The sent report is viewed on the "Sent Monthly" tab and disappears from the list of available draft reports 

- [x] Tapping on Cancel takes the user back to the report form.

Note! Keep the months in the reports in the format: month [in words] Year. Example: May 2021

**Comment by cafootitt** [comment]
@AnnieMungai I made some edits for clarification purposes and corrected a few navigation instructions. Please review. For the reports page, similar to ZEIR, this should be a single page, but the section headings can be collapsible. I don't think we want to have the user have to page through different pages of the report.

**Comment by cafootitt** [comment]
@AnnieMungai Please specify what illustration is to be used on the no draft reports page view.

**Comment by AnnieMungai** [comment]
@ellykits please use the icon on this screenshot for the no reports page. 
![image](https://user-images.githubusercontent.com/58034047/95186731-f8956900-07d2-11eb-830c-364eb1844ee5.png)

**Comment by AnnieMungai** [comment]
debug-v0.1.2
The different report sections are not completed.

**Comment by AnnieMungai** [comment]
V. 0.1.3-debug

Looks good
